<a href="https://colab.research.google.com/github/Pkun-college/Sendtex-tutorials/blob/main/Keith_galli/Keith_galli_pandas_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Datasets/pokemon_data.csv")

In [37]:
df.head(10)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,44,48,65,50,64,43,1,False

In [38]:
df.tail(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [39]:
print(df.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [40]:
print(df['Name'][:10])

0                    Bulbasaur
1                      Ivysaur
2                     Venusaur
3        VenusaurMega Venusaur
4                   Charmander
5                   Charmeleon
6                    Charizard
7    CharizardMega Charizard X
8    CharizardMega Charizard Y
9                     Squirtle
Name: Name, dtype: object

In [41]:
print(df['Legendary'][:10])

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Legendary, dtype: bool

In [42]:
df.iloc[1]

#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object

In [43]:
df.iloc[2,1]#R,C

'Venusaur'

In [44]:
for index, row in df.iterrows():
  print(index,row)

Streaming output truncated to the last 5000 lines.
Attack            50
Defense          100
Sp. Atk          100
Sp. Def          200
Speed             50
Generation         3
Legendary       True
Name: 415, dtype: object
416 #                   379
Name          Registeel
Type 1            Steel
Type 2              NaN
HP                   80
Attack               75
Defense             150
Sp. Atk              75
Sp. Def             150
Speed                50
Generation            3
Legendary          True
Name: 416, dtype: object
417 #                 380
Name           Latias
Type 1         Dragon
Type 2        Psychic
HP                 80
Attack             80
Defense            90
Sp. Atk           110
Sp. Def           130
Speed             110
Generation          3
Legendary        True
Name: 417, dtype: object
418 #                           380
Name          LatiasMega Latias
Type 1                   Dragon
Type 2                  Psychic
HP                           80
Attack                      100
Defense                     120
Sp. Atk                     140
Sp. Def                     150
Speed                       110
Generation                    3
Legendary                  True
Name: 418, dtype: object
419 #                 381
Name           Latios
Type 1         Dragon
Type 2        Psychic
HP                 80
Attack             90
Defense            80
Sp. Atk           130
Sp. Def           110
Speed             110
Generation          3
Legendary        True
Name: 419, dtype: object
420 #                           381
Name          LatiosMega Latios
Type 1                   Dragon
Type 2                  Psychic
HP                           80
Attack                      130
Defense                     100
Sp. Atk                     160
Sp. Def                     120
Speed                       110
Generation                    3
Legendary                  True
Name: 420, dtype: object
421 #                382
Name          Kyogre
Type 1         Water
Type 2           NaN
HP               100
Attack           100
Defense           90
Sp. Atk          150
Sp. Def          140
Speed             90
Generation         3
Legendary       True
Name: 421, dtype: object
422 #                             382
Name          KyogrePrimal Kyogre
Type 1                      Water
Type 2                        NaN
HP                            100
Attack                        150
Defense                        90
Sp. Atk                       180
Sp. Def                       160
Speed                          90
Generation                      3
Legendary                    True
Name: 422, dtype: object
423 #                 383
Name          Groudon
Type 1         Ground
Type 2            NaN
HP                100
Attack            150
Defense           140
Sp. Atk           100
Sp. Def            90
Speed              90
Generation          3
Legendary        True
Name: 423, dtype: object
424 #                               383
Name          GroudonPrimal Groudon
Type 1                       Ground
Type 2                         Fire
HP                              100
Attack                          180
Defense                         160
Sp. Atk                         150
Sp. Def                          90
Speed                            90
Generation                        3
Legendary                      True
Name: 424, dtype: object
425 #                  384
Name          Rayquaza
Type 1          Dragon
Type 2          Flying
HP                 105
Attack             150
Defense             90
Sp. Atk            150
Sp. Def             90
Speed               95
Generation           3
Legendary         True
Name: 425, dtype: object
426 #                               384
Name          RayquazaMega Rayquaza
Type 1                       Dragon
Type 2                       Flying
HP                              105
Attack                          180
Defense                         100
Sp. Atk                         180
Sp. Def                         100
Speed                           115
Generation                        3
Legendary                      True
Name: 426, dtype: object
427 #                 385
Name          Jirachi
Type 1          Steel
Type 2        Psychic
HP                100
Attack            100
Defense           100
Sp. Atk           100
Sp. Def           100
Speed             100
Generation          3
Legendary        True
Name: 427, dtype: object
428 #                            386
Name          DeoxysNormal Forme
Type 1                   Psychic
Type 2                       NaN
HP                            50
Attack                       150
Defense                       50
Sp. Atk                      150
Sp. Def                       50
Speed                        150
Generation                     3
Legendary                   True
Name: 428, dtype: object
429 #                            386
Name          DeoxysAttack Forme
Type 1                   Psychic
Type 2                       NaN
HP                            50
Attack                       180
Defense                       20
Sp. Atk                      180
Sp. Def                       20
Speed                        150
Generation                     3
Legendary                   True
Name: 429, dtype: object
430 #                             386
Name          DeoxysDefense Forme
Type 1                    Psychic
Type 2                        NaN
HP                             50
Attack                         70
Defense                       160
Sp. Atk                        70
Sp. Def                       160
Speed                          90
Generation                      3
Legendary                    True
Name: 430, dtype: object
431 #                           386
Name          DeoxysSpeed Forme
Type 1                  Psychic
Type 2                      NaN
HP                           50
Attack                       95
Defense                      90
Sp. Atk                      95
Sp. Def                      90
Speed                       180
Generation                    3
Legendary                  True
Name: 431, dtype: object
432 #                 387
Name          Turtwig
Type 1          Grass
Type 2            NaN
HP                 55
Attack             68
Defense            64
Sp. Atk            45
Sp. Def            55
Speed              31
Generation          4
Legendary       False
Name: 432, dtype: object
433 #                388
Name          Grotle
Type 1         Grass
Type 2           NaN
HP                75
Attack            89
Defense           85
Sp. Atk           55
Sp. Def           65
Speed             36
Generation         4
Legendary      False
Name: 433, dtype: object
434 #                  389
Name          Torterra
Type 1           Grass
Type 2          Ground
HP                  95
Attack             109
Defense            105
Sp. Atk             75
Sp. Def             85
Speed               56
Generation           4
Legendary        False
Name: 434, dtype: object
435 #                  390
Name          Chimchar
Type 1            Fire
Type 2             NaN
HP                  44
Attack              58
Defense             44
Sp. Atk             58
Sp. Def             44
Speed               61
Generation           4
Legendary        False
Name: 435, dtype: object
436 #                  391
Name          Monferno
Type 1            Fire
Type 2        Fighting
HP                  64
Attack              78
Defense             52
Sp. Atk             78
Sp. Def             52
Speed               81
Generation           4
Legendary        False
Name: 436, dtype: object
437 #                   392
Name          Infernape
Type 1             Fire
Type 2         Fighting
HP                   76
Attack              104
Defense              71
Sp. Atk             104
Sp. Def              71
Speed               108
Generation            4
Legendary         False
Name: 437, dtype: object
438 #                393
Name          Piplup
Type 1         Water
Type 2           NaN
HP                53
Attack            51
Defense           53
Sp. Atk           61
Sp. Def           56
Speed             40
Generation         4
Legendary      False
Name: 438, dtype: object
439 #                  394
Name          Prinplup
Type 1           Water
Type 2             NaN
HP                  64
Attack              66
Defense             68
Sp. Atk             81
Sp. Def             76
Speed               50
Generation           4
Legendary        False
Name: 439, dtype: object
440 #                  395
Name          Empoleon
Type 1           Water
Type 2           Steel
HP                  84
Attack              86
Defense             88
Sp. Atk            111
Sp. Def            101
Speed               60
Generation           4
Legendary        False
Name: 440, dtype: object
441 #                396
Name          Starly
Type 1        Normal
Type 2        Flying
HP                40
Attack            55
Defense           30
Sp. Atk           30
Sp. Def           30
Speed             60
Generation         4
Legendary      False
Name: 441, dtype: object
442 #                  397
Name          Staravia
Type 1          Normal
Type 2          Flying
HP                  55
Attack              75
Defense             50
Sp. Atk             40
Sp. Def             40
Speed               80
Generation           4
Legendary        False
Name: 442, dtype: object
443 #                   398
Name          Staraptor
Type 1           Normal
Type 2           Flying
HP                   85
Attack              120
Defense              70
Sp. Atk              50
Sp. Def              60
Speed               100
Generation            4
Legendary         False
Name: 443, dtype: object
444 #                399
Name          Bidoof
Type 1        Normal
Type 2           NaN
HP                59
Attack            45
Defense           40
Sp. Atk           35
Sp. Def           40
Speed             31
Generation         4
Legendary      False
Name: 444, dtype: object
445 #                 400
Name          Bibarel
Type 1         Normal
Type 2          Water
HP                 79
Attack             85
Defense            60
Sp. Atk            55
Sp. Def            60
Speed              71
Generation          4
Legendary       False
Name: 445, dtype: object
446 #                   401
Name          Kricketot
Type 1              Bug
Type 2              NaN
HP                   37
Attack               25
Defense              41
Sp. Atk              25
Sp. Def              41
Speed                25
Generation            4
Legendary         False
Name: 446, dtype: object
447 #                    402
Name          Kricketune
Type 1               Bug
Type 2               NaN
HP                    77
Attack                85
Defense               51
Sp. Atk               55
Sp. Def               51
Speed                 65
Generation             4
Legendary          False
Name: 447, dtype: object
448 #                  403
Name             Shinx
Type 1        Electric
Type 2             NaN
HP                  45
Attack              65
Defense             34
Sp. Atk             40
Sp. Def             34
Speed               45
Generation           4
Legendary        False
Name: 448, dtype: object
449 #                  404
Name             Luxio
Type 1        Electric
Type 2             NaN
HP                  60
Attack              85
Defense             49
Sp. Atk             60
Sp. Def             49
Speed               60
Generation           4
Legendary        False
Name: 449, dtype: object
450 #                  405
Name            Luxray
Type 1        Electric
Type 2             NaN
HP                  80
Attack             120
Defense             79
Sp. Atk             95
Sp. Def             79
Speed               70
Generation           4
Legendary        False
Name: 450, dtype: object
451 #                406
Name           Budew
Type 1         Grass
Type 2        Poison
HP                40
Attack            30
Defense           35
Sp. Atk           50
Sp. Def           70
Speed             55
Generation         4
Legendary      False
Name: 451, dtype: object
452 #                  407
Name          Roserade
Type 1           Grass
Type 2          Poison
HP                  60
Attack              70
Defense             65
Sp. Atk            125
Sp. Def            105
Speed               90
Generation           4
Legendary        False
Name: 452, dtype: object
453 #                  408
Name          Cranidos
Type 1            Rock
Type 2             NaN
HP                  67
Attack             125
Defense             40
Sp. Atk             30
Sp. Def             30
Speed               58
Generation           4
Legendary        False
Name: 453, dtype: object
454 #                   409
Name          Rampardos
Type 1             Rock
Type 2              NaN
HP                   97
Attack              165
Defense              60
Sp. Atk              65
Sp. Def              50
Speed                58
Generation            4
Legendary         False
Name: 454, dtype: object
455 #                  410
Name          Shieldon
Type 1            Rock
Type 2           Steel
HP                  30
Attack              42
Defense            118
Sp. Atk             42
Sp. Def             88
Speed               30
Generation           4
Legendary        False
Name: 455, dtype: object
456 #                   411
Name          Bastiodon
Type 1             Rock
Type 2            Steel
HP                   60
Attack               52
Defense             168
Sp. Atk              47
Sp. Def             138
Speed                30
Generation            4
Legendary         False
Name: 456, dtype: object
457 #               412
Name          Burmy
Type 1          Bug
Type 2          NaN
HP               40
Attack           29
Defense          45
Sp. Atk          29
Sp. Def          45
Speed            36
Generation        4
Legendary     False
Name: 457, dtype: object
458 #                             413
Name          WormadamPlant Cloak
Type 1                        Bug
Type 2                      Grass
HP                             60
Attack                         59
Defense                        85
Sp. Atk                        79
Sp. Def                       105
Speed                          36
Generation                      4
Legendary                   False
Name: 458, dtype: object
459 #                             413
Name          WormadamSandy Cloak
Type 1                        Bug
Type 2                     Ground
HP                             60
Attack                         79
Defense                       105
Sp. Atk                        59
Sp. Def                        85
Speed                          36
Generation                      4
Legendary                   False
Name: 459, dtype: object
460 #                             413
Name          WormadamTrash Cloak
Type 1                        Bug
Type 2                      Steel
HP                             60
Attack                         69
Defense                        95
Sp. Atk                        69
Sp. Def                        95
Speed                          36
Generation                      4
Legendary                   False
Name: 460, dtype: object
461 #                414
Name          Mothim
Type 1           Bug
Type 2        Flying
HP                70
Attack            94
Defense           50
Sp. Atk           94
Sp. Def           50
Speed             66
Generation         4
Legendary      False
Name: 461, dtype: object
462 #                415
Name          Combee
Type 1           Bug
Type 2        Flying
HP                30
Attack            30
Defense           42
Sp. Atk           30
Sp. Def           42
Speed             70
Generation         4
Legendary      False
Name: 462, dtype: object
463 #                   416
Name          Vespiquen
Type 1              Bug
Type 2           Flying
HP                   70
Attack               80
Defense             102
Sp. Atk              80
Sp. Def             102
Speed                40
Generation            4
Legendary         False
Name: 463, dtype: object
464 #                   417
Name          Pachirisu
Type 1         Electric
Type 2              NaN
HP                   60
Attack               45
Defense              70
Sp. Atk              45
Sp. Def              90
Speed                95
Generation            4
Legendary         False
Name: 464, dtype: object
465 #                418
Name          Buizel
Type 1         Water
Type 2           NaN
HP                55
Attack            65
Defense           35
Sp. Atk           60
Sp. Def           30
Speed             85
Generation         4
Legendary      False
Name: 465, dtype: object
466 #                  419
Name          Floatzel
Type 1           Water
Type 2             NaN
HP                  85
Attack             105
Defense             55
Sp. Atk             85
Sp. Def             50
Speed              115
Generation           4
Legendary        False
Name: 466, dtype: object
467 #                 420
Name          Cherubi
Type 1          Grass
Type 2            NaN
HP                 45
Attack             35
Defense            45
Sp. Atk            62
Sp. Def            53
Speed              35
Generation          4
Legendary       False
Name: 467, dtype: object
468 #                 421
Name          Cherrim
Type 1          Grass
Type 2            NaN
HP                 70
Attack             60
Defense            70
Sp. Atk            87
Sp. Def            78
Speed              85
Generation          4
Legendary       False
Name: 468, dtype: object
469 #                 422
Name          Shellos
Type 1          Water
Type 2            NaN
HP                 76
Attack             48
Defense            48
Sp. Atk            57
Sp. Def            62
Speed              34
Generation          4
Legendary       False
Name: 469, dtype: object
470 #                   423
Name          Gastrodon
Type 1            Water
Type 2           Ground
HP                  111
Attack               83
Defense              68
Sp. Atk              92
Sp. Def              82
Speed                39
Generation            4
Legendary         False
Name: 470, dtype: object
471 #                 424
Name          Ambipom
Type 1         Normal
Type 2            NaN
HP                 75
Attack            100
Defense            66
Sp. Atk            60
Sp. Def            66
Speed             115
Generation          4
Legendary       False
Name: 471, dtype: object
472 #                  425
Name          Drifloon
Type 1           Ghost
Type 2          Flying
HP                  90
Attack              50
Defense             34
Sp. Atk             60
Sp. Def             44
Speed               70
Generation           4
Legendary        False
Name: 472, dtype: object
473 #                  426
Name          Drifblim
Type 1           Ghost
Type 2          Flying
HP                 150
Attack              80
Defense             44
Sp. Atk             90
Sp. Def             54
Speed               80
Generation           4
Legendary        False
Name: 473, dtype: object
474 #                 427
Name          Buneary
Type 1         Normal
Type 2            NaN
HP                 55
Attack             66
Defense            44
Sp. Atk            44
Sp. Def            56
Speed              85
Generation          4
Legendary       False
Name: 474, dtype: object
475 #                 428
Name          Lopunny
Type 1         Normal
Type 2            NaN
HP                 65
Attack             76
Defense            84
Sp. Atk            54
Sp. Def            96
Speed             105
Generation          4
Legendary       False
Name: 475, dtype: object
476 #                             428
Name          LopunnyMega Lopunny
Type 1                     Normal
Type 2                   Fighting
HP                             65

In [45]:
df.loc[df['Legendary'] == True]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
156,144,Articuno,Ice,Flying,90,85,100,95,125,85,1,True
157,145,Zapdos,Electric,Flying,90,90,85,125,90,100,1,True
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
162,150,Mewtwo,Psychic,NaN,106,110,90,154,90,130,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [46]:
#df.iloc()# used specifically for integer finding
#df.loc()#used for finding using specific column values

In [47]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [48]:
df.sort_values('Name').head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False

Making changes to Data

In [49]:
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [50]:
#df['Total'] = df['HP'] + df['Attack']+ df['Speed']+ df['Defense']+ df['Sp. Atk']+ df['Sp. Def']

df['Total'] = df.iloc[:,4:10].sum(axis = 1) #axis = 1 => choosing columns

In [51]:
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [52]:
cols = list(df.columns.values)
df = df[cols[0:4] + [cols[-1]] + cols[4:12]]

In [53]:
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [56]:
df.to_excel('modified.xlsx', index = False)

Filtering Data

In [73]:
new_df = df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] > 70)]
new_df.reset_index(drop = True, inplace = True)
new_df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
1,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
2,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
3,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
4,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False

In [78]:
import re
df.loc[df['Type 1'].str.contains('fire|grass', flags = re.I, regex = True)] #flags = re.I to use without capitals

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

Conditional Changes

In [87]:
#df.loc[df['Type 1'] == 'Fire', 'Legendary'] = 'True'
df.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

Group By

In [107]:
df = pd.read_csv('/content/modified.csv')
#df.groupby(['Type 1']).mean().sort_values('HP', ascending=False)
#df.groupby(['Type 1']).sum().sort_values('HP',ascending = False)
df['Count'] = 1
df.groupby(['Type 1', 'Type 2']).count()['Count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: Count, Length: 136, dtype: int64

Working with very large datasets

In [112]:
new_df = pd.DataFrame(columns = df.columns)
for df in pd.read_csv('modified.csv', chunksize = 5):
  result = df.groupby(['Type 1']).count()
  new_df = pd.concat([new_df, result])
new_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Fire,1,1,NaN,0,1,1,1,1,1,1,1,1,1
Grass,4,4,NaN,4,4,4,4,4,4,4,4,4,4
Fire,4,4,NaN,3,4,4,4,4,4,4,4,4,4
Water,1,1,NaN,0,1,1,1,1,1,1,1,1,1
Bug,2,2,NaN,0,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Fairy,1,1,NaN,0,1,1,1,1,1,1,1,1,1
Flying,2,2,NaN,2,2,2,2,2,2,2,2,2,2
Fire,1,1,NaN,1,1,1,1,1,1,1,1,1,1
Psychic,2,2,NaN,2,2,2,2,2,2,2,2,2,2
Rock,2,2,NaN,2,2,2,2,2,2,2,2,2,2